# ============================================================================
# File: .github/workflows/frontend-build-deploy.yml
# Description: Build and deploy frontend - only on frontend changes
# ============================================================================

name: '🎨 Frontend Build & Deploy'

on:
  push:
    branches: [main]
    paths:
      - 'applications/frontend/**'
      - '.github/workflows/frontend-*.yml'
  pull_request:
    branches: [main]
    paths:
      - 'applications/frontend/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  IMAGE_NAME: frontend
  REGISTRY: gcr.io

jobs:
  build:
    name: 'Build Frontend'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: applications/frontend/package-lock.json

      - name: Install Dependencies
        working-directory: applications/frontend
        run: npm ci

      - name: Run Linter
        working-directory: applications/frontend
        run: npm run lint || echo "Lint not configured yet"

      - name: Run Tests
        working-directory: applications/frontend
        run: npm test || echo "Tests not configured yet"

      - name: Build Application
        working-directory: applications/frontend
        run: npm run build || echo "Build script not configured yet"

  docker-build-push:
    name: 'Docker Build & Push'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker Image
        working-directory: applications/frontend
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push to Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy Summary
        run: |
          echo "### ✅ Frontend Build Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Ready to deploy to GKE**" >> $GITHUB_STEP_SUMMARY
